### ISSUE TITLE
v1.0.2 actually has the "An error occurred communicating with Mopé. Please try again later." problem!

### ISSUE THREAD

**Issue by MrAnssaien** [Vokality/mope-php#2]
Hi there, 

Thank you so much for building this plugin. I'd like to inform you that v1.0.1 is more stable than v1.0.2. After my partner upgraded to v1.0.2 from v1.0.1, he started getting this error, "An error occurred communicating with Mopé. Please try again later." Luckily, I had the previous version stored on my PC, so when I downgraded to it, the payment gateway started working again.

**Comment by rhymiz** [comment]
Hey @MrAnssaien , I'll take a look. Do you mind providing some more background as to when this error occurs?
You should be able to see the reason for failure inside of the order status, that should help me figure what's going on.

**Comment by MrAnssaien** [comment]
Yeah, sure. With v1.0.2, as soon as I filled in the blanks on the checkout page, and I clicked "place order", I saw the error that was supposed to be fixed, which was ironic, considering that, like I said before, when I downgraded to 1.0.1, everything was fine. I also remember changing the timeout value for some reason. Could that be the problem?

**Comment by rhymiz** [comment]
I'll run some tests in my dev environment and issue a fix if needed tonight. Thanks for reporting the issue!

**Comment by MrAnssaien** [comment]
Don't mention it, man. Peace.

**Comment by rhymiz** [comment]
@MrAnssaien I've put up a bug fix for the above issue. 
Seems like `wp_remote_retrieve_response_code()` doesn't return an integer, and so the comparison failed. 
I'll be pushing a new release in a few minutes - sorry about the inconvenience.
